name: Android
on:
  push:
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04]
        qt_ver: [5.15.2]
        qt_target: [android]
        qt_arch: [android_armv7]
    steps:
      # - name: Install Qt
      #   uses: jurplel/install-qt-action@v2.10.0
      #   with:
      #     version: ${{ matrix.qt_ver }}
      #     target: ${{ matrix.qt_target }}
      #     arch: ${{ matrix.qt_arch }}
      #     tools: "tools_ifw,qt.tools.ifw.40,tools_qtcreator,4.14.0-0,qt.tools.qtcreator"
      #     setup-python: "false"
      #     aqtversion: ==1.2.5
      - name: Install Qt
        run: |
          sudo apt-get update
          sudo apt-get install build-essential libgl1-mesa-dev libxkbcommon-x11-0 libpulse-dev -y
          python3 -m pip install setuptools wheel
          python3 -m pip install py7zr==0.10.1
          python3 -m pip install aqtinstall==1.2.5
          python3 -m aqt install 5.15.2 linux android android -O /home/runner/work/summer-course-2021/Qt

      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Build for Android
        run: |
          export ANDROID_SDK_ROOT=$ANDROID_HOME
          export ANDROID_NDK_ROOT=$ANDROID_HOME/ndk-bundle
          export PATH=$PATH:~/work/summer-course-2021/Qt/5.15.2/android/bin/
          qmake
          make
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
