name: MacOS
on:
  push:

jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-10.15]
        qt_ver: [6.1.2]
        qt_arch: [clang_64]
    env:
      targetName: Junqi
    steps:
      - name: Install Qt
        uses: jurplel/install-qt-action@v2.13.0
        with:
          version: ${{ matrix.qt_ver }}
          cached: "false"
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Build on macOS
        run: |
          qmake
          make
      - name: Package
        run: |
          # 拷贝依赖
          macdeployqt ${targetName}.app -qmldir=. -verbose=1 -dmg

      - uses: actions/upload-artifact@v2
        with:
          name: ${{ env.targetName }}_${{ matrix.os }}_${{matrix.qt_ver}}
          path: ${{ env.targetName }}.app
